import React from "react";
import {
  useGetByPriceQuery,
  useGetCryptoAssetsQuery,
} from "@/shared/redux/cryptocurrency";
import { ICryuptoCurrency } from "@/shared/types/CryptoAsset";
import { Box, Paper, Typography } from "@mui/material";
import {
  DataGrid,
  GridColDef,
  GridRowsProp,
  GridToolbar,
} from "@mui/x-data-grid";
import { GridInitialStateCommunity } from "@mui/x-data-grid/models/gridStateCommunity";
import Head from "next/head";

const convertData = (data: ICryuptoCurrency[]) =>
  data.map((el, index) => {
    return {
      name: el.name,
      id: el.id,
      symbol: el.symbol,
      slug: el.slug,
      index: index,
      price: `USD   ${el.quote["USD"].price.toFixed(2)}`,
    };
  });

export const GRID_INITIL_STATE: GridInitialStateCommunity = {
  pagination: {
    paginationModel: { pageSize: 10, page: 0 },
  },
};
export default function Home() {
  const { data, isFetching } = useGetByPriceQuery();
  const rows: GridRowsProp = data?.data ? convertData(data.data) : [];

  const columns: GridColDef[] = [
    { field: "id", headerName: "Id", flex: 1 },
    { field: "name", headerName: "Name", flex: 1 },
    { field: "symbol", headerName: "Symbol", flex: 1 },
    { field: "price", headerName: "Price", flex: 1 },
  ];

  return (
    <>
      <Head>
        <title>Klever Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Paper>
        <Box p={2}>
          <Box mb={2} textAlign="center">
            <Typography variant="h4">
              The 10 most valuable cryptocurrencies today
            </Typography>
          </Box>
        </Box>

        <Box sx={{ display: "flex", height: 700 }} m={2}>
          <DataGrid
            rows={rows}
            columns={columns}
            loading={isFetching}
            initialState={GRID_INITIL_STATE}
            disableRowSelectionOnClick
          />
        </Box>
      </Paper>
    </>
  );
}
